sonarqube:
  image: sonarqube:6.7
  volumes:
    - ./target:/opt/sonarqube/extensions/plugins
  ports:
    - 9000:9000
    - 9092:9092

foreman:
  image: shakedl/foreman-analysis:latest
  links:
    - sonarqube
